// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuUcnO2GCmjgkbC71zb-MVzruZY199jtQ',
    appId: '1:318467325369:web:de71c3382780f1b2720a68',
    messagingSenderId: '318467325369',
    projectId: 'signasure-2025',
    authDomain: 'signasure-2025.firebaseapp.com',
    storageBucket: 'signasure-2025.firebasestorage.app',
    measurementId: 'G-76NWJTGMME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEE8qMJtMthxJpdnyzeU9pp3qqSHos5Yo',
    appId: '1:318467325369:android:cba99308e8f4836e720a68',
    messagingSenderId: '318467325369',
    projectId: 'signasure-2025',
    storageBucket: 'signasure-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR2uHu0gV0Y52vrsmOfvp7I_B8JRMDDmQ',
    appId: '1:318467325369:ios:9ce60574c97f9495720a68',
    messagingSenderId: '318467325369',
    projectId: 'signasure-2025',
    storageBucket: 'signasure-2025.firebasestorage.app',
    iosBundleId: 'com.example.signasure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR2uHu0gV0Y52vrsmOfvp7I_B8JRMDDmQ',
    appId: '1:318467325369:ios:9ce60574c97f9495720a68',
    messagingSenderId: '318467325369',
    projectId: 'signasure-2025',
    storageBucket: 'signasure-2025.firebasestorage.app',
    iosBundleId: 'com.example.signasure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuUcnO2GCmjgkbC71zb-MVzruZY199jtQ',
    appId: '1:318467325369:web:b3661ad96714015d720a68',
    messagingSenderId: '318467325369',
    projectId: 'signasure-2025',
    authDomain: 'signasure-2025.firebaseapp.com',
    storageBucket: 'signasure-2025.firebasestorage.app',
    measurementId: 'G-Q6LN2M7T70',
  );
}
